### ISSUE TITLE
saving directly opened template indicates incorrect result

### ISSUE THREAD

**Issue by ax-sc** [desklab/doku#39]
When saving a template, which was opened directly and not in the context of a document, the indication of the result shows an error even though the content is saved. The developer´s console shows an `Error: Request failed with status code 404`.

steps to reproduce:

1. Create a new Document with a new template.
2. Open the Template Editor directly from the document list.
3. Modify the content of the template.
4. Click on Save. (animated-notice will indicate `failed`)
5. Reload the page.

When using the Template-Editor in the context of a document, the animated-notice indicates `success` as expected.

**Comment by 3j14** [comment]
Hmm. This is probably because in the context of a document editor, changing the template will cause the variables to change. Thus, a request is made in order to update the document. This should not be done in the context of a template editor.

**Comment by 3j14** [comment]
It seems like this has already been fixed by commit a3404a0:

https://github.com/desklab/doku/blob/4aeb7c117ac5c7cac4a95abd13cf276f86730943/doku/static/src/store/modules/template.js#L22

`rootState.document.document.id !== undefined` already checks this action has been performed in a document context. However, now that we completely removed the template editor from the document editor, this should be save to be removed.

In the future, we should avoid chaining actions like these that depend on the context. Instead, I should have just fired two actions inside the vue.js component and check the context there.

**Comment by 3j14** [comment]
I'll close this for now, should be resolved.
